language: go
sudo: true 
install:
 - make deps
 - make build
go:
  - 1.5
  - 1.6
  - 1.7
script:
  - sudo sh ./ci/runtests.sh `echo $GOROOT` -c "cd $HOME/gopath/src/github.com/haukurk/latency-microservice-go; export GOPATH=$GOPATH"
