language: go
sudo: true 
install:
 - make deps
 - make build
go:
  - 1.3
  - 1.4
  - tip
script:
  - sudo sh ./ci/runtests.sh `which go` -c "$HOME/gopath/src/github.com/haukurk/latency-microservice-go"
